"""initial migration

Revision ID: fdfccde99e0e
Revises: 
Create Date: 2025-10-30 10:12:35.947454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfccde99e0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('roi', sa.Integer(), nullable=True),
    sa.Column('rent_1_day', sa.Integer(), nullable=True),
    sa.Column('prodit_15_day', sa.Integer(), nullable=True),
    sa.Column('year_profit', sa.Integer(), nullable=True),
    sa.Column('payback', sa.Integer(), nullable=True),
    sa.Column('annual_profit', sa.Integer(), nullable=True),
    sa.Column('invested', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_transaction_hash'), 'transaction', ['transaction_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referal_percent', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('gmail', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail')
    )
    op.create_table('user_car_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'car_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_car_association')
    op.drop_table('users')
    op.drop_index(op.f('ix_transaction_transaction_hash'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('cars')
    # ### end Alembic commands ###
